[project]
name = "seiri"
authors = [{ "name" = "tarolling" }]
version = "0.0.1"
description = "A project visualization tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.2.0",
]

[dependency-groups]
dev = ["ruff>=0.12.3"]
