services:
  dev:
    image: seiri-dev
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - RUST_BACKTRACE=1
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  cargo-cache:
  target-cache:
